### ISSUE TITLE
Shapefile results made of 15 objects

### ISSUE THREAD

**Issue by agrignard** [doorleyr/nyMobility#1]
@doorleyr What about having also in the results a shapefile (.shp or geojson) containing the 15 shapes corresponding to the string e.g Clinton,Chelsea etc 

It can be then be easier to instanciate anything from this folder

Does that sound doable?

**Comment by doorleyr** [comment]
Done, they're in the results folder.

**Comment by agrignard** [comment]
Ok cool

For the community it's ok for the Counties or Borough it would be nice to have the "exact" shape of the Counties/borough. Then It seems that for now the Staten Island is not in the census track let's see if we can include it

Let's see if we can converge to the official NYC Open Data 
https://data.cityofnewyork.us/City-Government/Borough-Boundaries/tqmj-j8zm

NB: Borough is a term for a part of New York City, and county is a term for a part of New York State. So you're right it's the same in term of Shape. As we are working on the NYC level I would be in favor to call it borough if we need to agree on a terminology. I am just anticipating the fact that borough/counties will be seen as specific object

**Comment by agrignard** [comment]
Ok let's forget about this file because it means we are producing a file that is supposed to be taken form a remove server.

IF the string in the OD are the same as the one in NYC then the filtering can be done directly for the raw file by parsing Community.geojson and Borough.geojson

**Comment by doorleyr** [comment]
The shapes should be exact now. I'll include Staten island as soon as I have the updated O-D data. I'm currently waiting for an email with a link to the data I requested.

**Comment by agrignard** [comment]
ok cool

I am trying ot have a generic parser. I am working both on your data and the one from NYC (so then I filtered the shape according to what is written in the OD.csv) However it seems that the census data (so the one used for allZonesCommm.geojson) and the NYC Opendata are not exactly structured the same way (I don't know why the parsing is slightly different).

**Comment by doorleyr** [comment]
Updated the allZones geojson files to have just properties of just 'Name and 'Type' so you should be able to parse it ans the Names should match the OD csv files.
